nombre_apellido = input("Ingrese nombre y apellido: ")
edad = int(input("Ingrese su edad: "))
altura = float(input("Ingrese su altura en metros: "))
peso = float(input("Ingrese su peso en kilogramos: "))
edad_futura = edad + 5
imc = peso / (altura ** 2)
print(f"¡Bienvenido/a al centro deportivo, {nombre_apellido}!")
print("----- Datos ingresados -----")
print(f"Nombre y apellido: {nombre_apellido}")
print(f"Edad: {edad} años")
print(f"Altura: {altura} m")
print(f"Peso: {peso} kg")
print("----- Resultados -----")
print(f"Dentro de 5 años tendrá {edad_futura} años.")
print(f"Su IMC es: {imc:.2f}")